"""
Profile routes: onboarding, photos, viewing and editing a profile.
"""
import re
from typing import Any, Dict

from fastapi import APIRouter, Depends, HTTPException

from auth import get_current_user
from database import get_utc_now, rescore_matches_for, users_collection
from models import OnboardingData, PhotosUpload
from moderation import assert_not_blocked
from serializers import PUBLIC_USER_PROJECTION, private_user, public_user

router = APIRouter(prefix="/api", tags=["profiles"])


@router.post("/onboarding/complete")
async def complete_onboarding(
    data: OnboardingData,
    current_user: dict = Depends(get_current_user)
):
    """Complete user onboarding"""
    update_data = {
        "profile.country": data.country,
        "profile.city": data.city,
        "profile.languages": data.languages,
        "profile.age": data.age,
        "profile.profession": data.profession,
        "profile.skills": data.skills,
        "profile.experience": data.experience,
        "profile.availability": data.availability,
        "profile.budget": data.budget,
        "profile.objectives": data.objectives,
        "profile.work_style": data.work_style,
        "profile.values": data.values,
        "profile.bio": data.bio,
        "onboarding_completed": True,
        "updated_at": get_utc_now()
    }
    
    await users_collection.update_one(
        {"user_id": current_user["user_id"]},
        {"$set": update_data}
    )
    
    return {"message": "Onboarding completed", "onboarding_completed": True}

@router.post("/profile/photos")
async def upload_photos(
    payload: PhotosUpload,
    current_user: dict = Depends(get_current_user)
):
    """
    Upload profile photos (base64 encoded, max 5).

    Wrapped in a Pydantic model: a bare `List[str]` parameter is read from the
    query string by FastAPI, so the JSON array the client posts was rejected with
    a 422 and onboarding silently lost every photo. The model also caps the
    payload size — base64 images live inside the user document, which MongoDB
    limits to 16 MB.
    """
    await users_collection.update_one(
        {"user_id": current_user["user_id"]},
        {"$set": {"profile.photos": payload.photos, "updated_at": get_utc_now()}}
    )

    return {"message": "Photos uploaded", "count": len(payload.photos)}

@router.get("/profile/{user_id}")
async def get_profile(
    user_id: str,
    current_user: dict = Depends(get_current_user)
):
    """Get another user's profile"""
    # Either side of a block hides the profile from the other
    await assert_not_blocked(current_user["user_id"], user_id)

    user = await users_collection.find_one(
        {"user_id": user_id},
        PUBLIC_USER_PROJECTION
    )

    if not user:
        raise HTTPException(status_code=404, detail="User not found")

    return public_user(user)

@router.post("/profile/update")
async def update_profile(
    updates: Dict[str, Any],
    current_user: dict = Depends(get_current_user)
):
    """Partial update of the current user's profile fields"""
    # Whitelist allowed profile fields for security
    allowed = {
        "name", "bio", "country", "city", "languages", "age",
        "profession", "skills", "experience", "availability",
        "budget", "objectives", "work_style", "values", "photos"
    }
    
    set_ops = {"updated_at": get_utc_now()}
    for key, value in updates.items():
        if key in allowed:
            set_ops[f"profile.{key}"] = value
    
    if len(set_ops) == 1:
        raise HTTPException(status_code=400, detail="No valid fields to update")
    
    await users_collection.update_one(
        {"user_id": current_user["user_id"]},
        {"$set": set_ops}
    )
    
    # Drop the cached AI narratives and reports for this user's pairs — they
    # describe the profile as it was. The id is escaped: user ids are generated by
    # us, but interpolating any value straight into $regex is how regex-injection
    # bugs get introduced later.
    from database import db as mongo_db
    await mongo_db.compatibility_cache.delete_many(
        {"pair_key": {"$regex": re.escape(current_user["user_id"])}}
    )

    # Existing matches store their score, so it has to be recomputed or the match
    # list keeps showing a score for the old profile. Free and local.
    await rescore_matches_for(current_user["user_id"])

    updated = await users_collection.find_one({"user_id": current_user["user_id"]})
    return private_user(updated)
