"""
Profile routes: onboarding, photos, viewing and editing a profile.
"""
import re
from typing import Any, Dict

from fastapi import APIRouter, Depends, HTTPException
from pydantic import ValidationError

import personality
from auth import get_current_user
from database import get_utc_now, rescore_matches_for, users_collection
from models import OnboardingData, PersonalityAnswers, PhotosUpload, ShowcaseUpdate
from moderation import assert_not_blocked
from serializers import PUBLIC_USER_PROJECTION, private_user, public_user

router = APIRouter(prefix="/api", tags=["profiles"])


async def _reprice_pairs(user_id: str) -> None:
    """
    Invalidate everything derived from this user's profile.

    Called after any change that feeds the compatibility engine. Two things go
    stale: the cached AI narratives (they describe the profile as it was) and the
    score stored on every existing match (the match list would keep showing the old
    number). Rescoring is local arithmetic, so it costs nothing.

    The id is escaped before going into `$regex`: user ids are generated by us, but
    interpolating any value straight into a regex is how injection bugs get
    introduced later.
    """
    from database import db as mongo_db

    await mongo_db.compatibility_cache.delete_many(
        {"pair_key": {"$regex": re.escape(user_id)}}
    )
    await rescore_matches_for(user_id)


@router.post("/onboarding/complete")
async def complete_onboarding(
    data: OnboardingData,
    current_user: dict = Depends(get_current_user)
):
    """Complete user onboarding"""
    update_data = {
        "profile.country": data.country,
        "profile.city": data.city,
        "profile.languages": data.languages,
        "profile.age": data.age,
        "profile.profession": data.profession,
        "profile.skills": data.skills,
        "profile.experience": data.experience,
        "profile.availability": data.availability,
        "profile.budget": data.budget,
        "profile.objectives": data.objectives,
        "profile.work_style": data.work_style,
        "profile.values": data.values,
        "profile.bio": data.bio,
        "onboarding_completed": True,
        "updated_at": get_utc_now()
    }
    
    await users_collection.update_one(
        {"user_id": current_user["user_id"]},
        {"$set": update_data}
    )
    
    return {"message": "Onboarding completed", "onboarding_completed": True}

@router.post("/profile/photos")
async def upload_photos(
    payload: PhotosUpload,
    current_user: dict = Depends(get_current_user)
):
    """
    Upload profile photos (base64 encoded, max 5).

    Wrapped in a Pydantic model: a bare `List[str]` parameter is read from the
    query string by FastAPI, so the JSON array the client posts was rejected with
    a 422 and onboarding silently lost every photo. The model also caps the
    payload size — base64 images live inside the user document, which MongoDB
    limits to 16 MB.
    """
    await users_collection.update_one(
        {"user_id": current_user["user_id"]},
        {"$set": {"profile.photos": payload.photos, "updated_at": get_utc_now()}}
    )

    return {"message": "Photos uploaded", "count": len(payload.photos)}

@router.put("/profile/showcase")
async def update_showcase(
    payload: ShowcaseUpdate,
    current_user: dict = Depends(get_current_user),
):
    """
    Replace the showcase — what this founder has built.

    A whole-list replace rather than add/remove endpoints, because order is part
    of the content: the first item is what someone sees first, and reordering
    through individual mutations is three round trips and a race between two
    devices.

    Deliberately not scored. What a founder shows says a great deal to a human
    reader and nothing an algorithm should be weighting, so this does not
    invalidate the compatibility cache the way editing skills does.
    """
    await users_collection.update_one(
        {"user_id": current_user["user_id"]},
        {"$set": {
            "profile.showcase": [
                {**item.model_dump(), "kind": item.kind} for item in payload.items
            ],
            "updated_at": get_utc_now(),
        }},
    )

    return {"showcase": payload.items, "count": len(payload.items)}


@router.get("/profile/{user_id}")
async def get_profile(
    user_id: str,
    current_user: dict = Depends(get_current_user)
):
    """Get another user's profile"""
    # Either side of a block hides the profile from the other
    await assert_not_blocked(current_user["user_id"], user_id)

    user = await users_collection.find_one(
        {"user_id": user_id},
        PUBLIC_USER_PROJECTION
    )

    if not user:
        raise HTTPException(status_code=404, detail="User not found")

    return public_user(user)

@router.post("/profile/update")
async def update_profile(
    updates: Dict[str, Any],
    current_user: dict = Depends(get_current_user)
):
    """Partial update of the current user's profile fields"""
    # Whitelist allowed profile fields for security
    allowed = {
        "name", "bio", "country", "city", "languages", "age",
        "profession", "skills", "experience", "availability",
        "budget", "objectives", "work_style", "values", "photos"
    }
    
    set_ops = {"updated_at": get_utc_now()}
    for key, value in updates.items():
        if key not in allowed:
            continue
        if key == "photos":
            # Same validation as the dedicated upload route. Without this, the
            # generic update was a way straight past it: it accepts a free-form
            # dict, so any URL at all could be written into a profile here.
            try:
                value = PhotosUpload(photos=value).photos
            except ValidationError as exc:
                raise HTTPException(status_code=422, detail=exc.errors())
        set_ops[f"profile.{key}"] = value
    
    if len(set_ops) == 1:
        raise HTTPException(status_code=400, detail="No valid fields to update")
    
    await users_collection.update_one(
        {"user_id": current_user["user_id"]},
        {"$set": set_ops}
    )
    
    await _reprice_pairs(current_user["user_id"])

    updated = await users_collection.find_one({"user_id": current_user["user_id"]})
    return private_user(updated)


# ===== Personality assessment =====

@router.get("/assessment/personality")
async def get_personality_assessment(current_user: dict = Depends(get_current_user)):
    """
    The questionnaire, plus whatever the current user has already answered.

    Returning the previous answers lets the client show the assessment as editable
    rather than one-shot — a founder's read on their own risk appetite changes as
    they get closer to committing.
    """
    stored = (current_user.get("profile") or {}).get("personality") or {}
    traits = personality.traits_of(current_user.get("profile"))

    return {
        "questions": personality.public_questions(),
        "scale": {"min": personality.MIN_ANSWER, "max": personality.MAX_ANSWER},
        "answers": stored.get("answers") or {},
        "traits": personality.describe(traits),
        "completeness": stored.get("completeness", 0),
        "completed_at": stored.get("completed_at"),
    }


@router.post("/assessment/personality")
async def submit_personality_assessment(
    payload: PersonalityAnswers,
    current_user: dict = Depends(get_current_user),
):
    """
    Score an assessment and fold it into this user's compatibility.

    Partial submissions are accepted: `alignment` renormalises over the traits both
    sides answered, so ten questions sharpen the score and four still help.
    """
    try:
        result = personality.score_answers(payload.answers)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))

    result["completed_at"] = get_utc_now()

    await users_collection.update_one(
        {"user_id": current_user["user_id"]},
        {"$set": {"profile.personality": result, "updated_at": get_utc_now()}},
    )

    # The assessment feeds `personality_score`, so every pair this user is in has a
    # stale number until it is recomputed.
    await _reprice_pairs(current_user["user_id"])

    return {
        "traits": personality.describe(result["traits"]),
        "completeness": result["completeness"],
        "completed_at": result["completed_at"],
    }
